parameters:
  extRepoUrl : ''
  configFile : ''
  helperBranch : ''
  testSuiteName : ''
  EnvironmentName : ''
  BuildShareFolder : ''
  RootSharePath : ''
  FilterSuffix : ''
  BuildPipelineName : ''
  RegressionPipelineNames : ''
  TargetRepoCsvFile : ''
  
jobs:
- job:
  displayName: Run regression
  pool: 
    name: TestSuiteBuildPool
  workspace:
    clean: false
  timeoutInMinutes: 0

  steps:
    - checkout: self
      path: 's'

    - checkout: git://${{parameters.extRepoUrl}}@${{parameters.HelperBranch}}

    - task: PowerShell@2
      displayName: "Trigger Test Suite Build"
      inputs:
        targetType: filePath
        filePath: "WindowsProtocolTestSuitesHelper/AzureScripts/Get-ExpandedDotNetCoreArchive.ps1"
        arguments: '-AccessToken "$(System.AccessToken)" -ApiUrl "$(build.apiUrl)" -BuildPipelineParameters "${{parameters[''build.buildPipelineParameters'']}}" -BuildPipelineName ${{parameters.BuildPipelineName}} -TargetRepoBranch "${{parameters[''build.targetRepoBranch'']}}" -ArchiveName "${{parameters[''build.archiveName'']}}" -ArtifactsLocalPath "$(Build.ArtifactStagingDirectory)/staging"'
      condition: succeeded()

    - task: PowerShell@2
      displayName: "Trigger Test Suite Local Regression"
      inputs:
        targetType: filePath
        filePath: "WindowsProtocolTestSuitesHelper/AzureScripts/Queue-DotNetCoreCodeLocalRegression.ps1"
        arguments: '-AccessToken "$(System.AccessToken)" -ApiUrl "$(build.apiUrl)" -LastBuildId "$(build.testSuiteBuildId)" -LastPipelineId "$(build.testSuitePipelineId)" -RegressionPipelineNames ${{parameters.RegressionPipelineNames}} -TargetHelperBranch ${{parameters.HelperBranch}} -TargetRepoCsvFile ${{parameters.TargetRepoCsvFile}} -TestFilter ${{parameters.FilterSuffix}}'
      condition: succeeded()

