parameters:
  extRepoUrl : ''
  configFile : ''
  helperBranch : ''
  testSuiteName : ''
  EnvironmentName : ''
  BuildShareFolder : ''
  RootSharePath : ''
  FilterSuffix : ''
  
jobs:
- job:
  displayName: Run regression
  pool: 
    name: TestSuiteBuildPool
  workspace:
    clean: false
  timeoutInMinutes: 0

  steps:
    - checkout: self
      path: 's'

    - checkout: git://${{parameters.extRepoUrl}}@${{parameters.HelperBranch}}

  - task: PowerShell@2
    displayName: "Trigger Test Suite Build"
    inputs:
      targetType: filePath
      filePath: "$(Build.Repository.LocalPath)/AzureScripts/Get-ExpandedDotNetCoreArchive.ps1"
      arguments: '-AccessToken "$(System.AccessToken)" -ApiUrl "$(build.apiUrl)" -BuildPipelineParameters "${{parameters[''build.buildPipelineParameters'']}}" -BuildPipelineName "${{parameters[''build.buildPipelineName'']}}" -TargetRepoBranch "${{parameters[''build.targetRepoBranch'']}}" -ArchiveName "${{parameters[''build.archiveName'']}}" -ArtifactsLocalPath "$(Build.ArtifactStagingDirectory)/staging"'
    condition: succeeded()

