trigger: none 

variables:
  - group: Build Variables


resources:
  repositories:
    - repository: template
      type: git
      name: WindowsProtocolTestSuites/WindowsProtocolTestSuites
      ref: AzurePipelines-main

jobs:
- job:
  displayName: DotNetCore Build
  pool: 
    vmImage: windows-2019
  workspace:
    clean: false
  timeoutInMinutes: 0

  steps:
  - template: pipelines/build/DotNetCore-Build-steps.yml@template