trigger: none 

variables:
  - group: External Repo Variables

resources:
  repositories:
    - repository: template
      type: git
      name: WindowsProtocolTestSuites/WindowsProtocolTestSuites
      ref: v-hazh/validate_pr_header_to_AzurePipelines_main

jobs:
- job:
  displayName: Verify Pull Requests
  workspace:
    clean: false
  timeoutInMinutes: 0

  steps:
  - template: pipelines/build/PullRequestBuild-steps.yml@template
    parameters:
      extRepoUrl: $(extRepo.url)
