trigger: none 

variables:
  - group: Azure Account
  - group: Build Variables
  - group: External Repo Variables
  - group: SMTP Account

resources:
  repositories:
    - repository: template
      type: git
      name: WindowsProtocolTestSuites/WindowsProtocolTestSuites
      ref: AzurePipelines-main

jobs:
  - template: pipelines/Integration_DotNetCore_Regression_steps.yml@template
    parameters:
      extRepoUrl: $(extRepo.url)
      HelperBranch: $(test.helperBranch)
      FilterSuffix: $(test.FilterSuffix)
      BuildPipelineName: $(test.BuildPipelineName)
      RegressionPipelineNames: $(test.RegressionPipelineNames)
      TargetRepoCsvFile: $(targetRepo.csvFile)
      targetRepoBranch: $(Build.SourceBranch)